Add basic support for hex codes in theme
zellij-org/zellij pull request #1092
Opened 2022-02-22 18:07 UTC by ramonGonzEdu

This pull request adds the ability to use hex codes in the config as strings.
The theme should follow the pattern:
`green: '#00FF00'`

This supports the `#FFFFFF` format and the `#FFF` format.

Please let me know if there are any issues as this is my first PR.

Possible Issues:
I had to remobe the Copy trait on `PaletteFromYaml` and `PaletteColorFromYaml` in order to ask for a string, but I am looking into serde's `deserialize_with` in order to move the verification step out of the `PaletteColor` conversion.

2022-02-22 18:08 UTC, ramonGonzEdu commented
This implements #880

2022-02-22 19:17 UTC, ramonGonzEdu commented
This assumes 255 as the color value if there is a parsing error. It also simply checks for string length (4 or 7) and ignores the first character

2022-02-24 07:21 UTC, a-kenji requested changes
Thanks for this work! This already looks very promising and is something we have been looking forward to for a while.

2022-02-24 07:21 UTC, a-kenji commented on zellij-utils/src/input/theme.rs
> +                    panic!("Invalid hex string");
Please convert this to an error, rather than a panic.

2022-02-24 07:21 UTC, a-kenji commented on zellij-utils/src/input/theme.rs
> +                    let red = u8::from_str_radix(hex_string.get(1..3).unwrap(), 16);
Same here, maybe check for the length prior to this step and return an error?

2022-03-25 23:48 UTC, ramonGonzEdu commented
Sorry for the late response, i was busy with classes, but I will work on those changes Tomorrow. :)

2022-06-21 20:50 UTC, ramonGonzEdu commented
Move to #1536

2022-06-21 20:50 UTC, closed without merging