fix paste freeze (#1366)
zellij-org/zellij pull request #1383
Opened 2022-05-06 08:08 UTC by tlinford

Resolve #1366 by offloading writes to a separate thread.

2022-05-10 16:15 UTC, raphCode commented
Can confirm that the deadlock is not happening with this PR, good work!

2022-05-13 15:00 UTC, imsnif requested changes
Hey @tlinford - thanks for the great troubleshooting on this!

I left some comments, mostly stylistic but I'm also unsure why we increased the channel bound by so much. I haven't tested this yet because I wanted to sort through that issue first. Once we do, I'll give this a thorough hammering and we'll make sure it's all good.

2022-05-13 15:16 UTC, tlinford commented on zellij-server/src/lib.rs
> +        channels::bounded(5000);
another oops, a leftover from my previous debuggin attempts

2022-05-14 16:41 UTC, tlinford commented
@imsnif cleaned it up, should be good for testing.

2022-05-16 18:37 UTC, raphCode commented
Seems to work for me!

2022-05-16 19:14 UTC, merged