fix: tab selection by left click in compact-bar
zellij-org/zellij pull request #1485
Opened 2022-06-10 20:12 UTC by amaihoefner

Fixes #1477

One thing I wasn't able to figure out:
It works when running "cargo make run -l compact"
but not when running "cargo make install ./test && ./test -l compact".

The latter seems to re-build the old version of the plugin and replace the wasm file in the "plugins" directory?
I don't know enough about WebAssembly / cargo make / the build process to be able to figure this one out.

Any pointers on how to fix this?
Or maybe someone more qualified can take over from here.

2022-06-10 20:57 UTC, a-kenji commented
@amaihoefner,
Thanks for the contribution!

The install just installs `zellij` itself, not the plugins. 
They only get installed on actual releases.

You can run `cargo make build-plugins-release`
And then run `zellij` with `zellij --data-dir ./target/dev-dir`

2022-06-11 05:40 UTC, amaihoefner commented
@a-kenji
Ah, that makes sense. Thanks for the info!
Following your instructions, it now works as expected.

2022-06-11 17:02 UTC, a-kenji requested changes
LGTM, please remove the asset itself, it will get build, optimized and included by our release script.

2022-06-11 18:43 UTC, a-kenji commented
Thank you!

2022-06-11 18:43 UTC, merged

2022-06-11 18:46 UTC, a-kenji reviewed
LGTM