Display controls line of status-bar plugin if pane size=1
zellij-org/zellij pull request #1875
Opened 2022-10-28 12:05 UTC by welcoMattic

Ref https://github.com/zellij-org/zellij/issues/1864

This PR will display only the controls line of status bar plugin if its pane has `size=1` instead of tip line.

The tip line is still displayed if `size=2`.

![image](https://user-images.githubusercontent.com/773875/198583259-c82fbdf9-e80a-45ab-bfc2-193daa0359be.png)

(FYI: it's my 1st PR on a Rust project, if it miss something let me know)

2022-10-31 16:45 UTC, imsnif requested changes
Hey @welcoMattic - looking great! Thanks for choosing us for your first Rust PR :)

I left a minor comment in the code. Otherwise, I think I'd rather not add another default layout for this so they won't get too crowded. We've now changed the plugin so it "does the right thing" if someone chooses to create such a layout.

After these changes, I'd be happy to merge.

2022-10-31 16:45 UTC, imsnif commented on default-plugins/status-bar/src/main.rs
> +        if _rows > 1 {
Let's change this to `rows` - it was previously prefixed with an underscore to denote that it's an unused variable in this function. Now we use it.

2022-10-31 17:38 UTC, welcoMattic commented
@imsnif Thanks for your review. I addressed your comments, I hope it's now ok for you ;)

2022-10-31 18:40 UTC, merged

2022-10-31 18:40 UTC, imsnif commented
Thanks @welcoMattic !

2023-01-09 17:44 UTC, panki27 commented
@welcoMattic does this still work for you?

I've tried this today with `zellij 0.34.4`. 
I'd love to only see the keybind hints, not the tips, but if I set `size=1` I don't get a status-bar at all anymore. With `size=2`, it works as normal.

Here is my layout:

```
layout {
    pane size=1 borderless=true {
        plugin location="zellij:tab-bar"
    }
    pane {
        pane 
    }
    pane size=1 borderless=true {
        plugin location="zellij:status-bar"
    }
}
```

2023-01-10 12:53 UTC, welcoMattic commented
@panki27 you are right, since last version it's broken. Can you open a new issue please?

2023-01-10 17:43 UTC, panki27 commented
@welcoMattic thank you for confirming!
I've created a new issue: #2077