Fix 2205 - Support cwd
zellij-org/zellij pull request #2290
Opened 2023-03-15 00:39 UTC by Kangaxx-0

#2205 - supports cwd as option

- [x] `Zellij options --default-cwd <path>` without config
- [x]  `Zellij` with `default_cwd` = <path> in zellij config file → set path to `usr`
- [x]   `cargo xtask test`

Screenshot

![2205](https://user-images.githubusercontent.com/85712372/225173249-711652df-ac76-4a21-8920-5010d7649d45.gif)

2023-03-15 16:40 UTC, imsnif requested changes
Hey @Kangaxx-0 - good job with this! The code looks great and the solution very native.

Only issue I found is that when the default_cwd is set, whenever we open a new pane it is set to it instead of the current folder. This to me is more of an `override_cwd` than a `default_cwd`.

If we adjust this, I think we're good to merge.

2023-03-16 01:37 UTC, Kangaxx-0 commented
> Only issue I found is that when the default_cwd is set, whenever we open a new pane it is set to it instead of the current folder. This to me is more of an `override_cwd` than a `default_cwd`.
> 
> If we adjust this, I think we're good to merge.

I changed it to `override_cwd` :)

2023-03-28 07:37 UTC, imsnif commented
Hey @Kangaxx-0 - I think we need a `default_cwd` rather than an `override_cwd` (that's also what the issue was about). Would you like to work on it in that direction?

2023-03-28 16:17 UTC, Kangaxx-0 commented
Hi @imsnif - Sorry, I am bit confused here.  In my initial commit, I used `default_cwd`, and I thought you would prefer `override_cwd` in your first comment, are you saying you feel `default_cwd` is better, and want me to change it back?

Besides the name change, any other change you feel we might need ?

2023-03-30 23:38 UTC, Kangaxx-0 commented
@imsnif Thanks for your feedback, I've made some small changes, and I believe it works as you expected.

I have not sent new iteration, this is just my local changes, please let me know when I will update the new commit

![defaultcwd](https://user-images.githubusercontent.com/85712372/228987773-d8210a23-ac68-476c-9b14-960dabc88cca.gif)

2023-04-06 09:19 UTC, imsnif commented
Hey @Kangaxx-0 - very elegant solution here! Only problem is that this now only works if a `default_shell` is defined... do you think we can find a solution that will work in any case?

2023-04-09 00:19 UTC, Kangaxx-0 commented
> Hey @Kangaxx-0 - very elegant solution here! Only problem is that this now only works if a `default_shell` is defined... do you think we can find a solution that will work in any case?

Hello @imsnif, thanks for your comments, in order to make default cwd works without `default_shell`, I made a few changes to pass down a new param.

I've tested all below scenarios and they all worked fine

- [x]  no `default_shell` and  no `default_cwd`
- [x] no `default_shell` and  `default_cwd`
- [x] `default_shell` and  no `default_cwd`
- [x] `default_shell` and `default_cwd`

Please take a look when you get a chance, thanks

2023-04-18 14:35 UTC, merged