feat: Add layout configuration to exclude panes from tab sync
zellij-org/zellij pull request #2314
Opened 2023-03-21 14:52 UTC by on3iro

Closes: #2285 

This PR adds the ability to configure panes to be excluded from receiving input when tab sync is activated.
I'm not sure if there is a better way than to add another parameter to the `write_to_pane_id`-function - so just let me know if I should change something.

I also did not find any tests in regard to tab syncing, so I also didn't add any.

If this PR gets merged I should probably also make an addition to the zellij website providing an example in the layouts section. I am just a bit unsure right now, how these two repos are being kept in sync. 
Should I already make the PR or should I wait until this PR might've been merged?

2023-03-29 08:05 UTC, imsnif requested changes
Hey @on3iro - this is great work. Good job threading the attribute, I imagine it was not trivial to figure out!

I left some comments in the code, and also I think there's a bit of a functionality issue. Using this layout:
```kdl
layout {
    pane
    pane split_direction="vertical" {
        pane
        pane exclude_from_sync=true
    }
}

```
If I start tab-sync, I can't write into the excluded pane even if I'm focused on it. Would you like to take a look?

2023-03-29 09:30 UTC, on3iro commented
> Hey @on3iro - this is great work. Good job threading the attribute, I imagine it was not trivial to figure out!
> 
> I left some comments in the code, and also I think there's a bit of a functionality issue. Using this layout:
> 
> ```
> layout {
>     pane
>     pane split_direction="vertical" {
>         pane
>         pane exclude_from_sync=true
>     }
> }
> ```
> 
> If I start tab-sync, I can't write into the excluded pane even if I'm focused on it. Would you like to take a look?

@imsnif thanks a lot for your kind words and feedback. I'll take a closer look at all the comments asap.
Regarding the functionality issue: I was aware of that behavior and it was a actually intentional on my side.
To me this behavior feels consistent, meaning that if I am inside sync mode, the pane should not receive input, no matter where I type. However I totally understand if you don't desire such behavior.
Should I try to make it so that the pane will always receive input when it is in focus? :)

2023-03-29 10:26 UTC, imsnif commented
> Should I try to make it so that the pane will always receive input when it is in focus? :)

Actually, this makes sense. Let's leave it like this.

2023-03-30 18:51 UTC, on3iro commented on zellij-utils/src/input/unit/layout_test.rs
> +    assert_snapshot!(format!("{:?}", layout));
sure, will do :)

2023-03-30 18:54 UTC, on3iro commented on zellij-server/src/tab/mod.rs
>                      Some(AdjustedInput::ReRunCommandInThisPane(command)) => {
Oh yeah. Good point. I totally missed that :+1:

2023-03-30 19:14 UTC, on3iro commented on zellij-server/src/tab/mod.rs
> +                        if !is_synced || !active_terminal.exclude_from_sync() {
Great idea!

2023-03-30 19:15 UTC, on3iro commented on zellij-server/src/tab/mod.rs
> +        is_synced: bool,
Yeah that makes sense. I somehow totally missed that I can just call the method and don't really need to drill the property down to the write method.

2023-03-30 19:16 UTC, on3iro commented
@imsnif I made the changes you requested. I kept them inside a separate commit for now, so they are easier to distinguish from the previous code. If you are satisfied with them you can just squash 'em :) 

Just let me know if there is anything else I should change :+1:

2023-04-06 08:53 UTC, imsnif commented
Hey @on3iro - the code changes look good, thanks! If you'd like to merge from main again, we can give this one last spin to make sure all is working and then merge. I'll try to get to it quickly after you merge in order not to create more drift!

2023-04-09 06:55 UTC, on3iro commented
Hey @imsnif - sorry for the late response. I am in the midst of moving into a new flat and super busy right now.
I will get back to this as soon as things have settled a bit. (probably around Thursday next week)

2023-04-15 08:17 UTC, on3iro commented
@imsnif I squashed my two branches and rebased onto `main` - everything should be fine and ready to merge now :) 🎉

2023-04-18 14:33 UTC, imsnif commented
Very nice work on this! I hope the move went well. Thank you for your patience.

2023-04-18 14:33 UTC, merged