feat(cwd-pane): Allow to open a new pane from the current working directory
zellij-org/zellij pull request #277
Opened 2021-04-18 18:12 UTC by qrasmont

PR for issue #102 

This allows to open a new pane in the current working directory of the active pane (using: <C-p> c).

Tested on both Linux and macOS.

2021-04-21 13:07 UTC, imsnif requested changes
Hey @qrasmont - this looks great and I'm sure it was quite a bit of work figuring out all the data paths.
Since this is a bit of a big change I'm going to take a closer look at it in the next few days. Meanwhile, I left one comment. And other than that, I think we don't need a special command for this. Let's make it the default behaviour.

2021-04-21 19:11 UTC, qrasmont commented on src/common/utils/proc.rs
> +}
Done

2021-04-21 19:12 UTC, qrasmont commented
I still need to figure out how I've broken some of the integration tests

2021-04-26 08:08 UTC, imsnif requested changes
Hey, great work once again on the changed. Thanks for being patient with my reviews taking a little bit of time and being somewhat fragmented (I'd ideally have liked to give all of this to you in one go, but times are a little hectic in Zellij right now :) ).

I left some comments in the code, and otherwise here's some issues I found so far:
1. This doesn't seem to work when I open a new tab. The new terminal there opens up in the default folder.
2. If the focused pane is a plugin (eg. `strider`), this crashes. To test this, start zellij with the strider layout: `zellij --layout strider`. Then move focus to the strider file explorer and open a new pane with alt-n.
3. Similarly to 2, if strider tries to open a new file, zellij crashes. (to reproduce: in strider try to press ENTER on a text file - make sure either the `EDITOR` or `VISUAL` env variable on your machine point to a text editor). I imagine this is for the same root cause as 2.

2021-04-26 08:08 UTC, imsnif commented on src/common/pty_bus.rs
> +    fn terminal_spawner(
Do you think we can either give this a more descriptive name or merge it with `spawn_terminal` somehow? I find it a little hard to understand the difference between these two methods without being aware of the whole cwd system...

2021-04-26 08:08 UTC, imsnif commented on src/client/tab.rs
> +            .unwrap();
I think this is the reason some of the tests are failing. Be sure to only send this instruction if the `active_terminal` has actually changed (eg. here move this inside the `else` block above).

2021-07-21 19:23 UTC, DAlperin commented
Hey @qrasmont do you still have time to work on this and get it ready to merge? If not, I can pick this up if that would be helpful.

2021-08-10 14:57 UTC, imsnif commented
Hey @DAlperin - since we haven't heard from @qrasmont lately, I think you can definitely pick this up if you want to. Either continuing from this PR or starting over. What do you think?

2021-08-14 01:54 UTC, DAlperin commented
Hey @imsnif I got a little busy this month but I think I can work on this a bit next week. I'll try and take this PR and rebase against main and put it in a new PR to start making the requested changes in.

2021-09-19 10:47 UTC, a-kenji commented
This is now implemented by #729, 
thanks to everyone working on it!

2021-09-19 10:47 UTC, closed without merging