[DRAFT]: Theme definition
zellij-org/zellij pull request #3242
Opened 2024-04-03 19:58 UTC by DeaconDesperado

Draft implementation of the specification laid out in #2297.  Would love feedback on this!

## Rough outline of the changes:

* Introduces a new struct, `Styling`, and the necessary protobuf records to match the spec from #2297 
* Implements KDL deserialization for `Styling`
* Provides bidirectional conversion for `Styling` <-> `Palette` in order to preserve backward compatibility for themes: 
  * Assignment of colors from the old palette to the new spec was reconstructed gradually by manual comparison. 
  * In some instances the same older named color may be used in multiple places (the new specification is more flexible and has more assignable styles, this only affects the default where user still has a `Palette` in their config).
* Preserve backward compatibility for plugins:
  * `Styling` -> `Palette` conversion is performed in the `plugin_api` layer, so the older message format is still propagated to plugins.
* Replace all references to named colors with style specifications

## Open questions / notes

### client_id_to_colors
 
[This function](https://github.com/zellij-org/zellij/blob/main/zellij-utils/src/data.rs#L16) is used to colorize pane frames and cursors in multi-user sessions.  While mentioned in some of the comments, the proposed specification in #2297 didn't explicitly lay these colors out, and there are (presently) 10 of them (larger in number than the other specs).  We could consider adding a separate style block for these, repurposing some of the emphases from `frame_unselected`, or using some sane defaults?  This draft presently sets them to values from `crate::shared::colors` for the time being.

### Configuration shape

KDL prohibits anonymous nodes, and lists are represented as sequential values after the node name.  In order to support all three representations of color presently used (single digit, 3 digit rgb, hex) the style specifications all are named individually, and macros from the original `Palette` are reused to deserialize the color, EG:

```
text_unselected {
  base "#DCD7BA"
  emphasis_1 "#ACD7CD"
  emphasis_2 "#DCD8DD"
  emphasis_3 "#DCD899"
  emphasis_4 "#ACD7CD"
  background "#16161D"
}
```

It's arguably a bit redundant to have these indexes named sequentially this way?  It might be possible to consolidate all the emphases to one list, but then that one node would need to be extracted into all 4 indexes somehow, which presents the prospect of mixing the EightBit/RGB/Hex representations...  WDYT?

Currently, `Styling`'s members are stored as fixed length arrays: it felt like a reasonable way to preserve the ability to add more colors in the future if needed.  An alternative could be this [structure though](https://github.com/DeaconDesperado/zellij/blob/2297-theme-kv/zellij-utils/src/data.rs#L770-L776).

### UI Components

Given that I'm only just getting familiar with the codebase, I opted to make these changes in place without also doing a migration of plugins to the various UI components 😅 .  The coloration should be consistent however, only preserving differences where they are an artifact of the present implementation.  

An example:  The `ribbon` implemented directly in the status-bar plugin uses alternating background colors to differentiate "tabs", whereas the UI component (eg in `session-manager`) uses divider spacers colored to match the terminal background.  Where encountered, these kinds of differences are preserved (for now).

### ThemeHue + PaletteSource

The swap of foreground/background based on `ThemeHue` is preserved only when converting a `Palette` to a `Styling`.  The only place I could find this value to be set was in [this function](https://github.com/zellij-org/zellij/blob/main/zellij-utils/src/shared.rs#L115), which doesn't seem to be called anywhere.  Perhaps it's leftover from an earlier implementation?  I seemed to uncover similar for `PaletteSource`.  Not sure if I'm missing something here...

### Strider

I was unfortunately unable to do as much vetting of strider specifically, encountered #3064 when trying to test it out.  Might require some help with this.

## Still TODO

In addition to incorporating any feedback, still need to:

* Update test suites that use `snapshot` assertion (temporarily ignored here)
* Investigate any e2e test suites that need to be updated

## Screenshots

<details>
<summary>Comparison of default theme (left new,  right old)</summary>
<br>
<img width="1226" alt="Screenshot 2024-04-03 at 1 17 21 PM" src="https://github.com/zellij-org/zellij/assets/380863/f1869e5e-f9c8-4b7f-a23e-0d8ff57bfd37" />
</details>

<details>
<summary>Welcome screen</summary>
<br>
<img width="1226" src="https://github.com/zellij-org/zellij/assets/380863/2e072c6e-9e07-4984-ab86-784136ef9c83" />
</details>

<details>
<summary>Frameless layout</summary>
<br>
<img width="1226" src="https://github.com/zellij-org/zellij/assets/380863/8f9a6e97-90cf-40b6-b980-c36b86ec05b5" />
</details>

<details>
<summary>Run pane exit codes</summary>
<br>
<img width="1226" src="https://github.com/zellij-org/zellij/assets/380863/c150f385-bc02-4c83-8ade-098be88ce225" />
<img width="1226" src="https://github.com/zellij-org/zellij/assets/380863/ef76b393-debd-4466-8f72-433537d12b8c" />
</details>

<details>
<summary>Simplified UI (no arrow fonts)</summary>
<br>
<img width="1226" src="https://github.com/zellij-org/zellij/assets/380863/cf7f44ef-b7a9-4288-92a5-93e71ac6091f" />
</details>

<details>
<summary>Compact layout</summary>
<br>
<img width="1226" src="https://github.com/zellij-org/zellij/assets/380863/610bdee4-995e-498b-9ef0-caacd1b6fa27" />
</details>

2024-04-03 20:30 UTC, imsnif commented
I'm very excited to see this happening!!

Just a heads up: I'm in the process of wrapping up v0.40.0 in the next week or so, so it will take me a short while to get to this. But rest assured, I will! I ask for your patience and thank you again for what seems like a tremendous amount of work!

2024-04-24 17:26 UTC, glenn-lytx commented
Is there a full config example for this? I'd like to grab this and compile it locally to test it out ..

2024-04-25 08:25 UTC, imsnif commented
Hey @DeaconDesperado - amazing and very thorough work here! Thank you for your patience and apologies for taking so long to give you an initial review. I'll try to be faster from now on so we can iterate over this quickly.

If it's alright with you, I prefer to go over the actual code changes once the product side (API, config, spec, behaviour, etc.) has been finalized. I think it'll save both of us some work, because changes in that area can cause sweeping changes in its implementation.

So to your questions:

> ## Open questions / notes
> ### client_id_to_colors

Good catch, we didn't account for these. Perhaps we can add a `multiplayer_user_ids` section to the theme definition?

> ### Configuration shape

> It's arguably a bit redundant to have these indexes named sequentially this way? It might be possible to consolidate all the emphases to one list, but then that one node would need to be extracted into all 4 indexes somehow, which presents the prospect of mixing the EightBit/RGB/Hex representations... WDYT?

I actually like it this way. I understand it can seem a bit redundant, but I think in the context of a theme configuration this is much clearer than `emphasis <color_1> <color_2> <color_3> <color_4>` - especially considering the different color formatting as you mentioned.

> Currently, `Styling`'s members are stored as fixed length arrays: it felt like a reasonable way to preserve the ability to add more colors in the future if needed. An alternative could be this [structure though](https://github.com/DeaconDesperado/zellij/blob/2297-theme-kv/zellij-utils/src/data.rs#L770-L776).

I don't have a strong opinion here, so up to you. A few considerations:
1. Performance (unless I'm wildly missing something) is not an issue for this feature whatsoever. So there's no need to be very cognizant of memory copying/cloning (in the context of the fixed-size arrays). Parsing the configuration is an order of magnitude slower, serializing the struct across the wasm boundary is an order of magnitude slower and otherwise sending it between threads is something that happens only on application startup (or configuration change) in which cases there are much slower things that happen as part of the process (eg. loading plugins, rendering, etc.)
2. If you decide to go with fixed-size arrays after all, I'd rather not have them in a public interface, and care needs to be taken in their setters so as not to crash ever if they overflow.
3. I usually prefer to be verbose in these sorts of things. If it were me I'd have a specialized struct similar to the one you mentioned with `emphasis_1`, `emphasis_2`, etc. as explicit members. But really - up to you.

> ### UI Components
> 
> Given that I'm only just getting familiar with the codebase, I opted to make these changes in place without also doing a migration of plugins to the various UI components 😅 . The coloration should be consistent however, only preserving differences where they are an artifact of the present implementation.

Legit! Let's keep things simple.

> ### ThemeHue + PaletteSource
> 
> The swap of foreground/background based on `ThemeHue` is preserved only [when converting](https://github.com/DeaconDesperado/zellij/blob/2297-theme-kv/zellij-utils/src/data.rs#L799-L811) a `Palette` to a `Styling`. The only place I could find this value to be set was in [this function](https://github.com/zellij-org/zellij/blob/main/zellij-utils/src/shared.rs#L115), which doesn't seem to be called anywhere. Perhaps it's leftover from an earlier implementation? I seemed to uncover similar for `PaletteSource`. Not sure if I'm missing something here...

Yes, these are legacies! It's totally fine to remove them if you want.

> ### Strider
These issues were fixed in v0.40.0 and iirc I even moved lots of stuff to UI components, so I hope this will make things easier!

Anything else I can do to help move this along?

2024-04-25 15:42 UTC, DeaconDesperado commented
@glenn-lytx below is a sample of the themes block I've been using locally, just need to change `theme_name` to suit:

```
themes {
  theme_name {
     styling {
          text_unselected {
              base "#DCD7BA"
              emphasis_1 "#ACD7CD"
              emphasis_2 "#DCD8DD"
              emphasis_3 "#DCD899"
              emphasis_4 "#ACD7CD"
              background "#16161D"
          }
          text_selected {
              base "#16161D"
              emphasis_1 "#ffa066"
              emphasis_2 "#16161D"
              emphasis_3 "#16161D"
              emphasis_4 "#16161D"
              background "#9CABCA"
          }
          ribbon_unselected     {
              base "#DCD7BA"
              emphasis_1 "#9CABCA"
              emphasis_2 "#7AA89F"
              emphasis_3 "#ACD7CD"
              emphasis_4 "#DCD819"
              background "#363646"
          }
          ribbon_selected {
              base "#16161D"
              emphasis_1 "#ffa066"
              emphasis_2 "#1A1A22"
              emphasis_3 "#2A2A37"
              emphasis_4 "#363646"
              background "#76946A"
          }
          table_title {
              base "#DCD7BA"
              emphasis_1 "#7FB4CA"
              emphasis_2 "#A3D4D5"
              emphasis_3 "#7AA89F"
              emphasis_4 "#DCD819"
              background "#252535"
          }
          table_cell_unselected {
              base "#DCD7BA"
              emphasis_1 "#DCD7CD"
              emphasis_2 "#DCD8DD"
              emphasis_3 "#DCD899"
              emphasis_4 "#ACD7CD"
              background "#1F1F28"
          }
          table_cell_selected {
              base "#16161D"
              emphasis_1 "#181820"
              emphasis_2 "#1A1A22"
              emphasis_3 "#2A2A37"
              emphasis_4 "#363646"
              background "#76946A"
          }
          list_unselected {
              base "#DCD7BA"
              emphasis_1 "#DCD7CD"
              emphasis_2 "#DCD8DD"
              emphasis_3 "#DCD899"
              emphasis_4 "#ACD7CD"
              background "#1F1F28"
          }
          list_selected {
              base "#16161D"
              emphasis_1 "#181820"
              emphasis_2 "#1A1A22"
              emphasis_3 "#2A2A37"
              emphasis_4 "#363646"
              background "#76946A"
          }
          frame_unselected {
              base "#DCD8DD"
              emphasis_1 "#7FB4CA"
              emphasis_2 "#A3D4D5"
              emphasis_3 "#7AA89F"
              emphasis_4 "#DCD819"
          }
          frame_selected {
              base "#76946A"
              emphasis_1 "#C34043"
              emphasis_2 "#C8C093"
              emphasis_3 "#ACD7CD"
              emphasis_4 "#DCD819"
          }
          exit_code_success {
              base "#76946A"
              emphasis_1 "#A3D5D5"
              emphasis_2 "#76946A"
              emphasis_3 "#76946A"
              emphasis_4 "#76946A"
          }
          exit_code_error {
              base "#C34043"
              emphasis_1 "#DCD819"
              emphasis_2 "#C34043"
              emphasis_3 "#C34043"
              emphasis_4  "#C34043"
          }
    }
  }
}
```

2024-04-25 20:47 UTC, glenn-lytx commented
> @glenn-lytx below is a sample of the themes block I've been using locally (also used in the screenshots), just need to change `theme_name` to suit:

Awesome, thanks! I'll give it a try

2024-06-07 18:50 UTC, DeaconDesperado commented
Revised this quite heavily with the suggested changes:

* Changed to an explicit struct, `StyleDeclaration`, in lieu of fixed size arrays + position indexing.
* Introduced a new type `MultiplayerColors` and handling for multi-user sessions.
* Corrected handling of styles in UI components (previous draft did not properly style tables and lists independent of styling in text).

To validate the behavior of the UI components, I set up a very simple toy example based on [rust-plugin-example](https://github.com/zellij-org/rust-plugin-example) that just renders all the elements in various states (with silly, but noticeable color differences between states)

![image](https://github.com/zellij-org/zellij/assets/380863/1c973843-1b73-468c-816f-38fbe1949bf6)

Let me know if the high level approach here now looks sound, and then I'll proceed with improving the test coverage for backward compatiblity and the aforementioned product stuff to support migration (docs, possible script to migrate old palette to new themes).  Also LMK if we prefer that in a separate PR.  Thanks!

2024-06-14 15:25 UTC, imsnif commented
Hey @DeaconDesperado - I'm happy to see the work going on. Kudos on your perseverance and consistency, this looks like quite a great effort!

I'm sorry it's taking me a bit of time to get to this, but rest assured - I plan to ASAP! I have not forgotten nor do I mean to let your work go to waste.

2024-06-21 08:43 UTC, imsnif commented
Hey @DeaconDesperado - this sounds good (though I will as mentioned wait with going over the exact code until we finalize the product stuff).

Including a conversion script is a very nice touch, but assuming we preserve backward compatibility and the existing themes will continue working as expected, I think it's alright. This is mostly meant to allow people to more easily create new themes with greater flexibility.

For the interests of efficiency, I have put aside some time every week on Friday morning CEST to go over this PR. So that you'll know when I'll do the next round and are able to prepare for it. I'll try to be available for quick questions in between so that we can get this going.

What else do you need from me for the time being?

2024-06-27 20:06 UTC, DeaconDesperado commented
@imsnif Didn't find time to put a cap on the sole failing integration test this week (alas day job!) but I was wondering what would be the best way to confirm with you the outstanding product related points?  Would you prefer a description incorporating any changes to what was discussed in #2297 here in the comments, or a separate PR to website repo that includes the user-facing documentation?

In the interest of providing something in time for the Friday review bandwidth you carved out for me (thanks!) I'll try to preemptively give the former here, updated to incorporate all the discussions we've had (this is also what's presently working):

# Updated Spec

Wherever colors are specified, they use the existing definition prior to this change, using any of:

* A hexadecimal string
* A triplet of u8 for TrueColor
* [A single u8 for a 256 terminal color](https://github.com/zellij-org/zellij/issues/2297#issuecomment-1933599289)

A theme consists of a `styling` block, containing:

`StyleDeclarations` to configure UI components.  Each accepts 6 colors: 
* A `base` color 
* 4 emphasis colors (`emphasis_1`,`emphasis_2`,`emphasis_3`,`emphasis_4`)
* A  `background` color.  

Any omitted declarations default to the [same fixed colors they would prior to this change](https://github.com/zellij-org/zellij/issues/2297#issuecomment-1938237509) (constructed from reverse engineering what named fixed colors mapped to what parts of the UX).  In order to make sure the theme is coherent, these declarations cannot be partially defined: if they are specified at all, all 6 colors must be set in them (or return an error at startup).  They are:

* `text_unselected` 
* `text_selected`
* `ribbon_unselected`
* `ribbon_selected`
* `table_title`
* `table_cell_unselected`
* `table_cell_selected`
* `list_unselected`
* `list_selected`

The following additional `StyleDeclarations` configure elements of the Zellij UI that are apart from the reusable components.  These are distinct from the above only in that they do not accept a `background` (since for all of them, the `text_unselected` background would apply).  As with above, these default to their existing fixed colors if left undefined, and if they are defined, all colors they expect must be included.  They are:

* `frame_unselected`: Colors the stroke around inactive panes
* `frame_selected`: Colors the stroke around active panes
* `exit_code_success`: Colors successful messages for panes started with `zellij run`
*  `exit_code_error`: Colors error messages for panes started with `zellij run`

And finally, a key `multiplayer_user_colors`, which defines ten colors `player_1, player_2, player_3 ... player_10`.  This specification, and the colors within it, are *optional*.  Any omitted will default to the [same fixed colors used prior to this change](https://github.com/zellij-org/zellij/blob/main/zellij-utils/src/data.rs#L28-L39).

<details open>
<summary>Complete example configuration for a named theme</summary>
<br>

```
themes {
  my_test_theme {
     styling {
          text_unselected {
              base "#DCD7BA"
              emphasis_1 "#ACD7CD"
              emphasis_2 "#DCD8DD"
              emphasis_3 "#DCD899"
              emphasis_4 "#ACD7CD"
              background "#16161D"
          }
          text_selected {
              base "#16161D"
              emphasis_1 "#ffa066"
              emphasis_2 "#16161D"
              emphasis_3 "#16161D"
              emphasis_4 "#16161D"
              background "#9CABCA"
          }
          ribbon_unselected     {
              base "#DCD7BA"
              emphasis_1 "#9CABCA"
              emphasis_2 "#7AA89F"
              emphasis_3 "#ACD7CD"
              emphasis_4 "#DCD819"
              background "#363646"
          }
          ribbon_selected {
              base "#16161D"
              emphasis_1 "#ffa066"
              emphasis_2 "#1A1A22"
              emphasis_3 "#2A2A37"
              emphasis_4 "#363646"
              background "#76946A"
          }
          table_title {
              base "#DCD7BA"
              emphasis_1 "#7FB4CA"
              emphasis_2 "#A3D4D5"
              emphasis_3 "#7AA89F"
              emphasis_4 "#DCD819"
              background "#252535"
          }
          table_cell_unselected {
              base "#DCD7BA"
              emphasis_1 "#DCD7CD"
              emphasis_2 "#DCD8DD"
              emphasis_3 "#DCD899"
              emphasis_4 "#ACD7CD"
              background "#1F1F28"
          }
          table_cell_selected {
              base "#16161D"
              emphasis_1 "#181820"
              emphasis_2 "#1A1A22"
              emphasis_3 "#2A2A37"
              emphasis_4 "#363646"
              background "#363636"
          }
          list_unselected {
              base "#23CF6D"
              emphasis_1 "#eb34ab"
              emphasis_2 "#eb99ab"
              emphasis_3 "#ebbbab"
              emphasis_4 "#ebddcb"
              background "#1F1F99"
          }
          list_selected {
              base "#ebae34"
              emphasis_1 "#ebcc66"
              emphasis_2 "#fcdd77"
              emphasis_3 "#fddd99"
              emphasis_4 "#ffffff"
              background "#353830"
          }
          frame_unselected {
              base "#DCD8DD"
              emphasis_1 "#7FB4CA"
              emphasis_2 "#A3D4D5"
              emphasis_3 "#7AA89F"
              emphasis_4 "#DCD819"
          }
          frame_selected {
              base "#76946A"
              emphasis_1 "#C34043"
              emphasis_2 "#C8C093"
              emphasis_3 "#ACD7CD"
              emphasis_4 "#DCD819"
          }
          exit_code_success {
              base "#76946A"
              emphasis_1 "#A3D5D5"
              emphasis_2 "#76946A"
              emphasis_3 "#76946A"
              emphasis_4 "#76946A"
          }
          exit_code_error {
              base "#C34043"
              emphasis_1 "#DCD819"
              emphasis_2 "#C34043"
              emphasis_3 "#C34043"
              emphasis_4  "#C34043"
          }
          multiplayer_user_colors {
              player_1 "#C34043"
              player_2 "#C34043"
              player_3 "#C34043"
              player_4 "#C34043"
              player_5 "#C34043"
              player_6 "#C34043"
              player_7 "#C34043"
              player_8 "#C34043"
              player_9 "#C34043"
              player_10 "#C34043"
          }
    }
  }
}
```

</details>

2024-06-28 09:55 UTC, imsnif commented
Hey @DeaconDesperado - thanks for putting this together. This is great and really helps me reviewing this PR quickly. I appreciate the clear communication and your meticulousness!

This looks really good to me and I hardly have any comments. Just a few things:

> Any omitted declarations default to the https://github.com/zellij-org/zellij/issues/2297#issuecomment-1938237509 (constructed from reverse engineering what named fixed colors mapped to what parts of the UX). In order to make sure the theme is coherent, these declarations cannot be partially defined: if they are specified at all, all 6 colors must be set in them (or return an error at startup).

To make sure I understand this correctly: an entire component can be omitted from the styling (eg. `ribbon_unselected`), but if a component is declared, all of its colors need to be set otherwise we get an error, right? (if I got this right - this is perfect).

> `text_selected`
Could we make this apply to the mouse-selection and search results too? These happen here: https://github.com/zellij-org/zellij/blob/main/zellij-server/src/panes/grid.rs#L1088 (and a few lines below in the same function)

> `frame_selected`
Could we also add a `frame_secondary` (I'm open to suggestions for a better name for this one). This is the color the frame changes to when we are in non-normal/locked mode (eg. `pane`, `tab` etc.) to let the user know their keyboard input will not be sent to the terminal pane in this mode. This will also in the future be the color of the frame under the mouse when we add mouse movement event tracking (it'll be something like: the frame under the mouse cursor will be this color, and you'll be able to select it and make it focused with a click and maybe do some other stuff like shift-click for multi-select and whatnot).

Otherwise - this looks very good and I'm happy to go forward with this and start reviewing the implementation once you're ready. Fair warning: I'm in the process of revamping the UI of the status-bar to solve the colliding keybindings issue, so I imagine I'm going to create some chaos there for you. I'll do my best to make it minimal and help with the merge afterwards.

Amazing work! Looking forward to iterating more and getting this merged.

2024-06-28 13:05 UTC, DeaconDesperado commented
@imsnif 

> To make sure I understand this correctly: an entire component can be omitted from the styling (eg. ribbon_unselected), but if a component is declared, all of its colors need to be set otherwise we get an error, right? (if I got this right - this is perfect).

That's correct.  I think it makes the most sense to have theme authors always provide a declaration in full or not at all, since partial application of defaults could lead to weird text / background mismatches.

> Could we make this apply to the mouse-selection and search results too?

> Could we also add a frame_secondary (I'm open to suggestions for a better name for this one).

I'll add these to the punchlist 😄.

>  I realized I didn't see any reference to this, so just to make sure: the old themes will still work, right? 

Yes, there is a [`From<Palettte>` impl that applies the members](https://github.com/zellij-org/zellij/pull/3242/files#diff-69611ba79cb44726e08c9207e00cffb933393ee0818fc11366c4860960394ee9R1302-R1428) of `Palette` retroactively to all the declarations they would have for a `Styling`.  It runs during configuration bootstrapping in the case that the `palette` key is in the kdl.  The plugin integration is via the protobufs, where a new field was added for these declarations, and another set of bidirectional mappings so that plugins are also kept backward compatible.

2024-06-29 06:46 UTC, imsnif commented
> Yes, there is a [`From<Palettte>` impl that applies the members](https://github.com/zellij-org/zellij/pull/3242/files#diff-69611ba79cb44726e08c9207e00cffb933393ee0818fc11366c4860960394ee9R1302) of `Palette` retroactively to all the declarations they would have for a `Styling`. It runs during configuration bootstrapping in the case that the `palette` key is in the kdl. The plugin integration is via the protobufs, where a new field was added for these declarations, and another set of bidirectional mappings so that plugins are also kept backward compatible.
> 
> Edit: As it is currently, the new vs old styles can't be mixed together and are configured disjointly. If your named theme includes a `styling` node, it uses the new configuration, then fallback to `palette`, then to absent.

Hey, I couldn't find the declaration in the link and I'm still not up to speed on the implementation details - so just to make sure (because this is a showstopper and I don't want to needlessly add work for you in the end): if I have an arbitrary file (not included in the Zellij repo) that has the old theme declaration with colors, that works now - will it continue working after this?

It's totally fine if we can't mix these declarations, but if that is the case, let's error if they are mixed.

2024-06-30 22:54 UTC, DeaconDesperado commented
Hmm the link does seem to be broken when highlighting the lines.

Yes, they will continue to work without problem.  The old format is just mapped into the new one in memory and at runtime when configuration loads.

2024-07-10 20:02 UTC, DeaconDesperado commented
I believe this should now be ready for review.  I added a few test cases to validate the configuration works as expected (and errors under the right conditions).

Per our separate discussion in Discord, I removed any commits I had made to the e2e tests in an effort to get them to work with my local setup (we ran into OSX environment-specific issues).  Will rely on the CI/CD feedback for these.

2024-07-12 08:44 UTC, imsnif commented
Hey @DeaconDesperado - first off: fantastic work once again! I had a list of things to check on the compatibility/API level and this implementation passed them with flying colors. The `[deprecated]` annotation for the protobuffers is a really nice touch (I didn't know such a thing existed).

This looks great all in all - I have a first round of rejects. Let's iterate over this a bit and once we're satisfied I'll do a deeper dive into the code

### 1. Regarding the `styling` node in the theme definition

I'm not sure if we discussed this before, but would it be possible to get rid of it and have everything flat? I think it'll be nicer for defining themes, eg.:

```kdl
  my_test_theme {
    text_unselected {
        base "#DCD7BA"
        emphasis_1 "#ACD7CD"
        emphasis_2 "#DCD8DD"
        emphasis_3 "#DCD899"
        emphasis_4 "#ACD7CD"
        background "#16161D"
    }
    text_selected {
        base "#16161D"
        emphasis_1 "#ffa066"
        emphasis_2 "#16161D"
        emphasis_3 "#16161D"
        emphasis_4 "#16161D"
        background "#9CABCA"
    }
}
```

### 2. The tab-bar active tab appears wrong
Using the provided theme example from above, I start Zellij and open a new tab.

![img-2024-07-12-094434](https://github.com/user-attachments/assets/a048eda2-e533-4761-b1ac-b6cde066d5f3)

### 3. The new "keygroup separator" needs to be themed as well
Might be able to fold it in to one of the existing theme definitions? Otherwise maybe we can add a separate definition for it. You're more in the weeds on this one, so maybe you have an idea? (the orange ribbon in this screenshot). This screenshot is from when the default_mode is `locked`, but it will now also show every time you enter a mode that is not "normal" or "locked" with the default settings.

![img-2024-07-12-101721](https://github.com/user-attachments/assets/c3364d62-8b4b-4205-9e5b-5243fef51759)

### 4. The session-manager "New Session" Screen appears wrong
This is a screenshot from the `test-theme`, notice that the up/down arrows do not appear on the selected row, and also the text is not readable (though the latter might be a specific issue with this theme definition?)

![img-2024-07-12-102403](https://github.com/user-attachments/assets/c73c69cd-7349-47a7-a22e-71b0910cf348)

### 5. The session-manager "Resurrect Session" Screen appears wrong
This might be the same issue as `4`, but just wanted to mention it here.

Also, there appears to be a separator between table columns (both in a selected and non-selected row). Can we remove it?

![img-2024-07-12-102727](https://github.com/user-attachments/assets/bcf6b990-5853-4e7d-9893-2f680575de4b)


## Conclusion
I'm very excited to see this moving forward so consistently. The example theme also looks amazing. Looking forward to the next iteration.

2024-07-12 21:25 UTC, DeaconDesperado commented
Thanks!  Once I managed to understand how the plugin API works it felt a bit natural to anticipate certain backward compatibility needs there (it's very nicely designed!)

### 1 

We can remove this, yeah.  The thought behind it had been that perhaps there could be a separate node `colors` where named aliases for colors could be declared to be used instead of repeatedly listing the color codes in for each declaration.  Since [KDL's schema definition doesn't presently support union types](https://github.com/kdl-org/kdl/discussions/371), it also felt maybe a bit more future proof to map a single node directly to a struct in case we ever wanted to do KDL schema validation for the configs and need to add other stuff that's configurable via a theme.

### 2 

Pushed two commits to fix this, quick oversight on my part to not backport the same fix from the UI ribbon component into its separate implementations in tab-bar + compact-bar .

### 3  

This presently uses one of the emphasis colors that would map for `orange` from the older theme definition: `ribbon_selected.emphasis_2`.  Since it has only a single color with no text overlaid, and is active when a mode is selected, I thought maybe we reuse one of the already existing emphases colors since it's semantically close? 

### 4/5  

I suspect the disappearing text is in fact the test theme, if you're testing with the one I pasted in the comment earlier I had to rearrange a few definitions.  I'll paste a new one in a following comment. 

Will definitely look to collapse that extra space between cells as well.

One other thing: in testing some of the existing themes as-is (dracula) I'm noticing that by prohibiting partial application of colors, we might make it impossible to make some elements keep transparency?  EG you must provide a `background` attribute for `table_cell_unselected`now, whereas the preceding designs keep this transparent:

Dracula original:

![image](https://github.com/user-attachments/assets/8dc532a3-336e-4b0f-bedf-b673d6ca2679)

Dracula now:

![image](https://github.com/user-attachments/assets/ad8c30b4-4128-4611-8380-54c28ca4ee0b)

Perhaps it makes sense to make background optional?

2024-07-12 21:27 UTC, DeaconDesperado commented
<details open>
<summary>Updated test theme</summary>
<br>

```
themes {
  test_theme {
     styling {
          text_unselected {
              base "#DCD7BA"
              emphasis_1 "#ACD7CD"
              emphasis_2 "#DCD8DD"
              emphasis_3 "#DCD899"
              emphasis_4 "#ACD7CD"
              background "#16161D"
          }
          text_selected {
              base "#16161D"
              emphasis_1 "#ffa066"
              emphasis_2 "#16161D"
              emphasis_3 "#16161D"
              emphasis_4 "#16161D"
              background "#9CABCA"
          }
          ribbon_unselected     {
              base "#DCD7BA"
              emphasis_1 "#9CABCA"
              emphasis_2 "#7AA89F"
              emphasis_3 "#ACD7CD"
              emphasis_4 "#DCD819"
              background "#363646"
          }
          ribbon_selected {
              base "#16161D"
              emphasis_1 "#ff0066"
              emphasis_2 "#ffa066"
              emphasis_3 "#2A2A37"
              emphasis_4 "#363646"
              background "#76946A"
          }
          table_title {
              base "#DCD7BA"
              emphasis_1 "#7FB4CA"
              emphasis_2 "#A3D4D5"
              emphasis_3 "#7AA89F"
              emphasis_4 "#DCD819"
              background "#252535"
          }
          table_cell_unselected {
              base "#DCD7BA"
              emphasis_1 "#DCD7CD"
              emphasis_2 "#DCD8DD"
              emphasis_3 "#DCD899"
              emphasis_4 "#ACD7CD"
              background "#1F1F28"
          }
          table_cell_selected {
              base "#16161D"
              emphasis_1 "#181820"
              emphasis_2 "#1A1A22"
              emphasis_3 "#2A2A37"
              emphasis_4 "#363646"
              background "#DCD7BA"
          }
          list_unselected {
              base "#23CF6D"
              emphasis_1 "#eb34ab"
              emphasis_2 "#eb99ab"
              emphasis_3 "#ebbbab"
              emphasis_4 "#ebddcb"
              background "#1F1F99"
          }
          list_selected {
              base "#ebae34"
              emphasis_1 "#ebcc66"
              emphasis_2 "#fcdd77"
              emphasis_3 "#fddd99"
              emphasis_4 "#ffffff"
              background "#353830"
          }
          frame_unselected {
              base "#DCD8DD"
              emphasis_1 "#7FB4CA"
              emphasis_2 "#A3D4D5"
              emphasis_3 "#7AA89F"
              emphasis_4 "#DCD819"
          }
          frame_selected {
              base "#76946A"
              emphasis_1 "#C34043"
              emphasis_2 "#C8C093"
              emphasis_3 "#ACD7CD"
              emphasis_4 "#DCD819"
          }
          frame_highlight {
              base "#DCD819"
              emphasis_1 "#DCD819"
              emphasis_2 "#DCD819"
              emphasis_3 "#DCD819"
              emphasis_4 "#DCD819"
          }
          exit_code_success {
              base "#76946A"
              emphasis_1 "#A3D5D5"
              emphasis_2 "#76946A"
              emphasis_3 "#76946A"
              emphasis_4 "#76946A"
          }
          exit_code_error {
              base "#C34043"
              emphasis_1 "#DCD819"
              emphasis_2 "#C34043"
              emphasis_3 "#C34043"
              emphasis_4  "#C34043"
          }
          multiplayer_user_colors {
              player_1 "#C34043"
              player_2 "#C34043"
              player_3 "#C34043"
              player_4 "#C34043"
              player_5 "#C34043"
              player_6 "#C34043"
              player_7 "#C34043"
              player_8 "#C34043"
              player_9 "#C34043"
              player_10 "#C34043"
          }
    }
  }
}
```

</details>

2024-07-19 11:18 UTC, imsnif commented
> ### 1
> 
> We can remove this, yeah. The thought behind it had been that perhaps there could be a separate node `colors` where named aliases for colors could be declared to be used instead of repeatedly listing the color codes in for each declaration. Since [KDL's schema definition doesn't presently support union types](https://github.com/kdl-org/kdl/discussions/371), it also felt maybe a bit more future proof to map a single node directly to a struct in case we ever wanted to do KDL schema validation for the configs and need to add other stuff that's configurable via a theme.

I hear you and I appreciate the thoughts about leaving room for future improvements, but in general I tend to prefer the present, especially when it comes to user experience. We can work around this in the future if we ever decide to do schema validation, and we can always add an `alias` node for example to prevent repetition. On the other hand, removing a layer of indentation in a potentially large configuration makes things considerably easier and more readable to users.

> ### 3
> 
> This presently uses one of the emphasis colors that would map for `orange` from the older theme definition: `ribbon_selected.emphasis_2`. Since it has only a single color with no text overlaid, and is active when a mode is selected, I thought maybe we reuse one of the already existing emphases colors since it's semantically close?

Hmm... could we use the text 0 emphasis? I think it also maps to the default orange and that's what it uses presently. I feel this would be easier for theme authors to figure out and will likely cause less contrast issues (since it appears on the same background as the text).


> Perhaps it makes sense to make background optional?

I see what you mean... I agree making background optional would solve this issue, but then we'd still be left with the similar (and previously existing) issue of the background color between the ribbons (also seen in the screenshot). Maybe we can solve both of these problems with a different solution? eg. reuse the `background` definition from the previous themes?

2024-08-09 13:14 UTC, DeaconDesperado commented
@imsnif Yes I'm not blocked (except for having a few other things come up that took some bandwidth!). Still very interested in taking this over the hump, just need to integrate the config changes for another review.

2024-08-20 14:21 UTC, imsnif commented
I'm very sorry, but I think I probably caused some mess for you: https://github.com/zellij-org/zellij/pull/3559

Let me know if you need help with the merge.

2024-09-10 18:11 UTC, DeaconDesperado commented
No worries @imsnif I think I should be able to work through it but will reach out if needed.  Have had some delays getting back to this (new baby 👶 at home) but will try to have the next review ready next week!

2024-09-28 19:25 UTC, DeaconDesperado commented
It took awhile to get everything sorted, but I managed to get the rebased version working and am back to working on the remaining open feedback.  Hope to have next review up soon!

2024-10-18 01:21 UTC, DeaconDesperado commented
Apologies for the long delay on this, but happy to report it is rebased successfully and ready for the next set of eyes again.

There's one known issue I'm aware of (and could definitely use some guidance with!).  For some of the existing themes (eg Nord), some conflicts emerge when mapping the `Palette` struct into the newer spec.  For example, the `text_unselected` style declaration applies to all instances of the `Text` ui component.  This is used both in the `tab-bar` plugin's swap layout indicator, where its background should take the color of the top tab bar, and in `strider`'s file listing view, where its background should take the terminal background color (be transparent).

Screenshot:

<img width="1006" alt="image" src="https://github.com/user-attachments/assets/d296b9c8-de9b-4834-858f-72436e5acf51">

I noticed some discussion in #3658 on a similar topic but still need to digest it 😄

2024-10-21 13:41 UTC, imsnif commented
Hey @DeaconDesperado - happy to see you're still pitching away at this and am excited to see the progress! Also, congratulations on your new baby and I hope all is going well there.

I hope it's alright with you if I defer a full review until we settle the text-background issue (more on this below). It will be easier for me because at this point getting back into context on the whole thing is a lot of mental load :sweat_smile: 

So this was also noticed as you mentioned in https://github.com/zellij-org/zellij/pull/3681. The solution we came up with is to have `Text` components default to a transparent background (i.e. no background color and using the terminal's background), and have the ability to define them as "opaque" in which case they'll take the existing theme's "black" background. This solved the issue you also found and demonstrated in the screenshot above.

To me it seems like we could adopt a similar solution to the new themes (maintaining backwards compatibility with the `opaque` specification) by having `Text` components either not have a background (the default) or setting the background specified in the theme if they are `opaque`. What do you think?

2024-10-27 00:35 UTC, DeaconDesperado commented
@imsnif That's sounds like a great solution as it will allow the component's caller to specify the opacity (eg plugin authors).

Seems like it was recently merged so I'll work towards rebasing that in.

2024-11-01 19:25 UTC, DeaconDesperado commented
The opacity method worked out great to solve the above problem.  I also rebased in some of the newer plugins (`plugin-manager` and `configuration`) and changed them to support the new style definition in this latest change set.

I think with that, all the known issues should be resolved.  Let me know if there's anything I can do to support a review (happy to find a time to coordinate on discord for example, if that helps).

2024-11-02 08:18 UTC, imsnif commented
Sounds amazing! I'm very impressed by your hard work and perseverance. Looking forward to having this merged.

That being said, this release is all set to go out next week and right now I'm mostly finalizing the last bits. So I'll be sure to take another look at this in 1-2 weeks max once things settle down. Just wanted to give you a heads up and let you know I have not forgotten.

It'll make it easier for me if maybe you can add a sample theme with all options to the example folder for easy testing (assuming one is not already available, I have not yet looked at the code).

Thank you for your patience!

2024-12-13 10:46 UTC, feketegy commented
> Hey @DeaconDesperado - sorry for taking longer to get back to this. I want to see this merged for next version and am now making it a priority. What theme are you using for testing? Could you paste it here or point me at it? I plan on playing with this a little and then moving to the code once we're satisfied with the functionality.
> 
> I plan on iterating on this fast from my side, no more weeks of waiting!

This is the only feature that keeps me from using zellij

2024-12-13 10:53 UTC, imsnif commented
Friends, let's please try to keep things on topic here. Thanks!

2024-12-17 02:11 UTC, DeaconDesperado commented
@imsnif No worries on the delay.  My own test theme is copied below.  I have also been testing with other included themes like Nord and Dracula to make sure the backward compatibility works correctly.

<details><summary>Theme</summary>

```
text_unselected {
          base "#DCD7BA"
          emphasis_1 "#ACD7CD"
          emphasis_2 "#DCD8DD"
          emphasis_3 "#DCD899"
          emphasis_4 "#ACD7CD"
          background "#16161D"
      }
      text_selected {
          base "#16161D"
          emphasis_1 "#ffa066"
          emphasis_2 "#16161D"
          emphasis_3 "#16161D"
          emphasis_4 "#16161D"
          background "#9CABCA"
      }
      ribbon_unselected     {
          base "#DCD7BA"
          emphasis_1 "#9CABCA"
          emphasis_2 "#7AA89F"
          emphasis_3 "#ACD7CD"
          emphasis_4 "#DCD819"
          background "#363646"
      }
      ribbon_selected {
          base "#16161D"
          emphasis_1 "#ff0066"
          emphasis_2 "#ffa066"
          emphasis_3 "#2A2A37"
          emphasis_4 "#363646"
          background "#76946A"
      }
      table_title {
          base "#DCD7BA"
          emphasis_1 "#7FB4CA"
          emphasis_2 "#A3D4D5"
          emphasis_3 "#7AA89F"
          emphasis_4 "#DCD819"
          background "#252535"
      }
      table_cell_unselected {
          base "#DCD7BA"
          emphasis_1 "#DCD7CD"
          emphasis_2 "#DCD8DD"
          emphasis_3 "#DCD899"
          emphasis_4 "#ACD7CD"
          background "#1F1F28"
      }
      table_cell_selected {
          base "#16161D"
          emphasis_1 "#181820"
          emphasis_2 "#1A1A22"
          emphasis_3 "#2A2A37"
          emphasis_4 "#363646"
          background "#DCD7BA"
      }
      list_unselected {
          base "#23CF6D"
          emphasis_1 "#eb34ab"
          emphasis_2 "#eb99ab"
          emphasis_3 "#ebbbab"
          emphasis_4 "#ebddcb"
          background "#1F1F99"
      }
      list_selected {
          base "#ebae34"
          emphasis_1 "#ebcc66"
          emphasis_2 "#fcdd77"
          emphasis_3 "#fddd99"
          emphasis_4 "#ffffff"
          background "#353830"
      }
      frame_unselected {
          base "#DCD8DD"
          emphasis_1 "#7FB4CA"
          emphasis_2 "#A3D4D5"
          emphasis_3 "#7AA89F"
          emphasis_4 "#DCD819"
      }
      frame_selected {
          base "#76946A"
          emphasis_1 "#C34043"
          emphasis_2 "#C8C093"
          emphasis_3 "#ACD7CD"
          emphasis_4 "#DCD819"
      }
      frame_highlight {
          base "#DCD819"
          emphasis_1 "#DCD819"
          emphasis_2 "#DCD819"
          emphasis_3 "#DCD819"
          emphasis_4 "#DCD819"
      }
      exit_code_success {
          base "#76946A"
          emphasis_1 "#A3D5D5"
          emphasis_2 "#76946A"
          emphasis_3 "#76946A"
          emphasis_4 "#76946A"
      }
      exit_code_error {
          base "#C34043"
          emphasis_1 "#DCD819"
          emphasis_2 "#C34043"
          emphasis_3 "#C34043"
          emphasis_4  "#C34043"
      }
```

</details>

2024-12-19 10:08 UTC, imsnif commented
Hey @DeaconDesperado - thanks! Great work on this, I'm really stoked to see this taking shape. Here's another round of review (tested with the default theme but this is also present in the test-theme):

1. The `Text` elements seem to have lost their boldness in some cases (some examples I've seen: the `Ctrl g` in the status-bar in the "unlock-first" preset and the help text in the configuration screen (`Ctrl o` + `c` by default))
2. The non-colored elements in the `configuration` have turned gray rather than the original white
3. When the elements in the `configuration` "Change mode behavior" screen are selected, their colors are inverted to green for non-colored and red for the emphases
4. In general (continuing with point 3) I think the emphasis colors in selected elements (nested list and text) are off (no color gets us green, I think?)
5. The selected background does not appear for nested lists (eg. in the configuration "change mode behavior" screen)

In general - this PR has driven home the point for me that deciding to opt-out of tests for styling in Zellij was a mistake on my part! Unfortunately though, not one that can be easily fixed for the time being though. So I guess we're going to have to do some old-style eyeball comparison between the old and new UI elements to make sure nothing changed. Thankfully, the default plugins (session-manager - `Ctrl o` + `w`, plugin-manager - `Ctrl o` + `p`, configuration `Ctrl o` + `c`, welcome-screen `zellij -l welcome`, and the status-bar/tab-bar) use most if not all permutations of these plugins.

That being said, I'm happy to help with the side-by-side comparisons as I did here above since I know these interfaces quite well and know where to look.

2024-12-20 19:16 UTC, DeaconDesperado commented
@imsnif 

> So I guess we're going to have to do some old-style eyeball comparison between the old and new UI elements to make sure nothing changed. 

This is the method I have been using for the most part, swapping theme configurations between terminal windows and doing eyeball comparisons.

> That being said, I'm happy to help with the side-by-side comparisons as I did here above since I know these interfaces quite well and know where to look.

I'm extremely grateful for your help with that... I doubt that I have enough personal familiarity with all of Zellij's different features to have a good sense of when something's off in all the various views.  Case in point, issue #3 and #4 above were easily identifiable by looking at that `configuration` pane of the session mode, which was new to me at least 😄 

The latest push above is rebased on main and includes fixes for all the stuff from the list.

2024-12-20 23:09 UTC, jokeyrhyme commented
I wonder if we can identify pairs of elements that are expected to have good contrast, e.g. text on background

And have unit tests that assert that contrast is sufficient? For every included theme? 

I wouldn't expect identification of 100% of such pairs, and I'd expect the definition of contrast would need to be quite generous to start with in order to not complain about existing themes

Just an initial framework with some obvious cases would be a great start

2024-12-26 15:23 UTC, imsnif commented
Thanks for the suggestion @jokeyrhyme. This PR has been going on for the better part of a year and I think it would be best not to add features on top of it - in the interests of seeing it merged in a timely manner.

2024-12-26 15:26 UTC, imsnif commented
Hey @DeaconDesperado - great work once more. I've spent some time with this and found a few more minor issues:

1. In the session-manager, in the "Resurrect session" tab, the selected line has wrong emphasis colors
2. In the session-manager, in the "New session" tab, the text entered in the "New session name:" field has the wrong color (in the default theme it's green and it should be orange)
3. In the session-manager, in the "New session" tab, the folder selected in "New session folder:" should also be orange and now it's green (probably the same issue as point 2?)

Otherwise, I created a `theme-tester` plugin to allow you to quickly iterate over this without looking through all the Zellij menus. It renders all UI elements and their permutations: https://github.com/imsnif/theme-tester/tree/main

Lastly, I tried the test theme but couldn't get it to work. Maybe I'm doing something wrong, or maybe something was lost in the merge? Here's what I did: I copied it verbatim into my config and then changed `theme` to `test_theme`. It did not live-reload and was also not applied when I restarted Zellij... any clues?

2024-12-29 21:11 UTC, DeaconDesperado commented
@imsnif This plugin is very helpful, thanks for brewing that up quickly!  Makes it rather easy to see defects in the conversion of an older theme to this newer format for anything using the UI components.

Unfortunately since the session-manager is not yet using the components, it required a few piecemeal fixes.  But should be addressed now (I also eyeball checked all the stuff in that plugin again).  Both are now pushed here.

WRT the test theme, I only included the body nodes of the named theme in my paste, which was oversight on my part since it wouldn't give a good idea of the config.  If copied verbatim that probably wouldn't parse as is.  I updated the above comment to include the full structure ( outer `test_theme` and the setting for `theme` by name itself) so can give that another go.

2025-01-10 09:48 UTC, imsnif commented
Hey @DeaconDesperado - I'm back from vacation and here's another round of review. Bottom-line, this looks very good and stable. There are only 2 UI issues and a handful of small functionality issues that I found. Once we get these fixed we can move to review the code itself (not promising I won't notice other functional/UI issues on the way, but I did a pretty thorough go-over, so it's less likely!)

1. When a command pane exits in the default theme, the `<ENTER> re-run, <ESC> drop to shell, <Ctrl-c> exit` line should have an orange emphasis and right now it has a magenta one
2. If it's not too much work, would it be possible to change the emphases indices so that they start with 0? This will match the plugin API and make things easier, but not a must!
3. The `table_title`/`table_cell_unselectd` `background` attribute doesn't seem to be working (when I change them they don't have any effect)
4. The `list_unselected` `background` attribute also doesn't seem to be working
5. `frame_unselected` doesn't seem to be working?
6. Question: Are the emphasis colors on the `frame_selected`/`frame_unselected` used for things like the `ENTER`, `ESC` , `Ctrl-c`, etc. on command panes? If so, they don't seem to be working...
7. I see the `exit_code_success` and `exit_code_failure` attributes also have emphases... I think here they are not relevant? Or am I missing something?
8. `text_unselected`/`background` doesn't change the background of text, but rather seems to change the background of the status and tab bars
9. frame highlight doesn't seem to be working at all (even with the default and old themes). Afaict it takes the color of the frame_selected (just to be clear: this is the color of the frame when we are in a non-base mode, eg. `PANE` or `TAB`).

2025-01-11 19:43 UTC, DeaconDesperado commented
Welcome back, hope you had a nice vacation!

1). This should now be corrected, was indeed the wrong index.
2). Yeah this had occurred to me as well late in the refactor 😅.  I agree it's a good improvement, I will do it (will just take a bit of time).
3 + 4). I think we might need to clarify the intended behavior here, specifically as it relates to the new `opaque` settings of the text used within those components.  I believe right now their backgrounds only show if the text included with them has `opaque` tripped to `true` (if not it's a bug, will verify).  Maybe it should activate for both unconditionally?  It would mean however that there's no way to render a transparent list / table, which seems to be the current behavior: tables just have a text color but no background?
5). This should now be corrected, I had a wildcard match branch returning a `None` where `frame_unselected` should be used.
6). Not currently, no.  The only real usage of `frame_selected` and `frame_unselected` at present is the `base` value, used to color the stroke around the frames and the names (eg `Pane 1`).  I had understood [your suggestion in this comment](https://github.com/zellij-org/zellij/issues/2297#issuecomment-1933599289) to mean emphasis colors should be included to potentially be used by plugins in the future.
7). I use these in the loading indicator only.  Similar to 6 though, they're intended for highlights on text in error or success messages more generally by plugins.  Perhaps more general names like `success_message` and `error_message` would be clearer? 
8).  This is a very similar issue as to 3 + 4, where keeping consistent behavior with for existing themes conflicts a bit with the functionality we're trying to add (I think?).  The status + tab bars presently use a background color determined by `ThemeHue`, which is then set alike on the foreground color for the arrow characters to give the illusions of negative space.  These plugins don't yet make use of the ui components.  In an attempt to map them as they would be used, we assume `Text` will be used for the prefix (` Zellij {session_name_goes_here}`).  And then assign the matching colors over to the arrow splitter chars.  As for other text not getting styled, it's the same situation with `opaque` not being tripped to `true` (it defaults false).
9). This is now fixed, oversight on my part! 😓

2025-01-17 09:23 UTC, imsnif commented
Hi again!

1. Great!
2. Cool, no worries - thanks!
3 + 4 + 8. I see what you mean - that makes sense. I think it's something we'll have to clarify in the documentation so that it doesn't confuse theme authors, but otherwise it's alright to leave it as is.
5. Cool
6. Alright
9. No worries, looks great now!

One other issue that I found now (I guess because of some of the fixes here) is that in the default theme the unselected frame is orange rather than colorless.

I think if we fix this last issue and take care of 2, the functionality is done and we can move on to review the code.

Great work as always!

2025-01-23 14:17 UTC, DeaconDesperado commented
The outstanding two issues should now be resolved:

* Orange is no longer incorrectly applied for `frame_highlight` in the default theme and conversion of themes in the older format.  This did require a small workaround, I left a comment capturing the reasoning for when we get to the code review.
* Shifted the naming for `emphasis_*` to be zero indexed

Also rebased in the latest changes.

2025-01-28 10:54 UTC, imsnif requested changes
Hey, so I've gone over the code - great stuff! You've done a really thorough and high quality job and I hardly have any comments. I especially liked the cleanup around the UI components where we've added functionality but the code has grown terser and more simplified.

A few issues:
1. We need to update the snapshots in the tests (`cargo insta review`)
2. One more functional issue: after looking through the code, I remembered `simplified_ui` (this is an option to allow users to forego the arrow glyphs in the UI) and then tested it, and many of the colors appear wrong (especially in the tab bar with multiple tabs). Could you give it a look? (start Zellij with `zellij options --simplified-ui true`). I haven't looked in all the places, but I guess by now you know most of them. Let me know if you're unsure and want another pair of eyes.
3. Regarding protobuffs: I looked through the code and I *think* this is the case, but I haven't tested this personally - so I just want to be 100% sure: we still send the old deprecated colors along with the new one, right? This is very important and we'll likely have to keep doing this forever in order to keep supporting old plugins.
4. Also regarding protobuffs, I like the addition of the `deprecated` field to the definitions in order to make it clear to SDK authors, but it adds a compilation warning to Zellij. Any way around this? If not we might want to reconsider given point 3.

Otherwise, I'm tagging @dj95 here. If you have the time, could you take this branch out for a spin with zjstatus to see if it doesn't break things for you? Specifically talking about user themes and colors, in UI components as well as palette definitions.

2025-01-28 10:54 UTC, imsnif commented on zellij-utils/src/input/config.rs
> +    fn omitting_required_style_errors() {
<3

2025-01-28 10:54 UTC, imsnif commented on zellij-utils/src/kdl/mod.rs
> +                // Older palette based theme definition
Very nice

2025-01-28 10:54 UTC, imsnif commented on default-plugins/session-manager/src/ui/components.rs
> +// It will be obviated once everything is migrated to UI components from zellij-tile
:+1:

2025-01-28 19:09 UTC, DeaconDesperado commented on zellij-server/src/panes/unit/snapshots/zellij_server__panes__grid__grid_tests__ribbon_ui_component.snap
> +00 (C):  [1m<[38;5;9mn[39;38;5;0m> RESIZE 
This should now be resolved (and the corresponding snapshots reverted).  It resulted from unconditionally including escape sequences for index coloration even when no indexes were set.

2025-01-28 21:06 UTC, DeaconDesperado commented
1. These should now be updated, and the two changed snapshots have been reverted after fixing a bug I had created by always rendering the control sequences for index-based coloration even in cases where no index colors are actually set.
2. I have also fixed this:  I had checked that simplified UI awhile ago, but some of the subsequent fixes reassigned some of the colors.  It should be correct in the latest push.
3. Yes, we alway transmit the older representation of color, `Palette`, in the protobufs in order to keep backward compatibility.  It's also bidirectionally translated, so a theme implemented in the new style gets mapped back into a `Palette` during protobuf serialization so that plugins expecting the older format can understand the settings from the newer Zellij host.
4. I was able to add an allow attribute to the relevant struct to squelch the warning in Zellij itself.  Usage by plugins should still get the warning (will be helpful in that context, I think).

I think the `None` for frame_highlight is the only outstanding thing I'm aware of, responded inline to your source comment there.

2025-01-28 21:12 UTC, DeaconDesperado commented on zellij-utils/src/data.rs
> +                base: PaletteColor::EightBit(7),
I can think of two ways to resolve this, curious what your preference would be:

1. Make a special variant of `StyleDeclaration` with an option for `base`.  

2. Have some sort of sentinel value for this field, only used here in the Palette -> Theme conversion, that when detected will still coerce a `None` for `frame_highlight` under default.  It will have the benefit of no special struct case just for this one `StyleDeclaration`, but would have the drawback that the actual color represented by that sentinel value wouldn't be usable for `frame_highlight` (arguably pretty confusing).

2025-01-31 10:34 UTC, imsnif commented on zellij-utils/src/data.rs
> +                base: PaletteColor::EightBit(7),
I'd definitely prefer option `1`. Maybe call the variant `NoColor` or `NoStyling` to make it clearer? Wdyt?

2025-01-31 10:37 UTC, imsnif commented
Hey, took this for another spin and all the issues seem good to me! I replied in-line to the frame-highlight issue. Otherwise, I ran the CI again and if all is well I'm going to give this another week to see if we get any comments from @dj95 (no pressure at all!!) and then I'm happy to merge.

After this is merged, I'll write up some documentation for this and would be happy to get your input if you'd be up for it.

2025-01-31 15:58 UTC, dj95 commented
Hi, first of all, thanks a lot for asking me for feedback. I really appreciate that. It's one of the favorite features, I wish for a long time for. It looks awesome and I had a lot of fun tinkering around with the theme spec while testing it. 

In the first tests, I've tested zjstatus (my status bar plugin with some custom rendering), which works totally fine. No issues at all. 

However, I've found some smaller issues within the ui components. If there's something I did wrong on my end, please don't hesitate to point it out. I can also provide the code for testing it, in case you are interested.

### `.opaque()` is not working properly

UI components implement a `.opaque()` function, to explicitly draw the background explicitly. This will help with terminals, that draw the background when it's set, as some behave different when the background color is the same as the transparent background color of the terminal. More details can be found it the following pr: https://github.com/zellij-org/zellij/pull/3681 . 

With the new theme spec pull request, some of the ui components do not draw the opaque background anymore. I've used my default zellij config (with a modified gruvbox theme) and the dracula theme spec from within this pull request. Both produced the issue. 

<img width="1800" alt="Screenshot 2025-01-31 at 16 42 26" src="https://github.com/user-attachments/assets/cfd6704d-cad2-4bd1-80d8-a5bccfe30d10" />

On the left side is the new version from this pull request, on the right side the current zellij release.

### Ribbons do not seem to render properly

As the screenshot also depicts, ribbons do not seem to render correctly with the ui components. The orange foreground in ribbon 2 is due to my theme change, so that's not an issue :D it's just that the end-chars of the power line arrows do not seem to render correctly. The last arrow also somehow got extended by another empty space.


### Table rows without any style have another color

This one might not be an issue, but a good behavior change. I just want to mention it because I've noticed, that it differs from the current behavior of the main branch. The first row of the table in the screenshot on the left now uses the foreground color instead of the orange (or green from the default theme).


---

For reference, here's the config and the code:

<details>
<summary>config.kdl</summary>

```javascript
theme "test_theme"
themes {
  test_theme {
    fg 235 219 178
    bg "#504945"
    black "#3c3836"
    red "#cc241d"
    green "#d79921"
    yellow "#d79921"
    blue "#458588"
    magenta "#b16286"
    cyan "#689d6a"
    white "#fbf1c7"
    orange "#d79921"

    // text_unselected {
    //         base 255 255 255
    //         background 0 0 0
    //         emphasis_0 255 184 108
    //         emphasis_1 139 233 253
    //         emphasis_2 80 250 123
    //         emphasis_3 255 121 198
    //     }
    //     text_selected {
    //         base 255 255 255
    //         background 40 42 54
    //         emphasis_0 255 184 108
    //         emphasis_1 139 233 253
    //         emphasis_2 80 250 123
    //         emphasis_3 255 121 198
    //     }
    //     ribbon_selected {
    //         base 0 0 0
    //         background 80 250 123
    //         emphasis_0 255 85 85
    //         emphasis_1 255 184 108
    //         emphasis_2 255 121 198
    //         emphasis_3 98 114 164
    //     }
    //     ribbon_unselected {
    //         base 0 0 0
    //         background 248 248 242
    //         emphasis_0 255 85 85
    //         emphasis_1 255 255 255
    //         emphasis_2 98 114 164
    //         emphasis_3 255 121 198
    //     }
    //     table_title {
    //         base 80 250 123
    //         background 0
    //         emphasis_0 255 184 108
    //         emphasis_1 139 233 253
    //         emphasis_2 80 250 123
    //         emphasis_3 255 121 198
    //     }
    //     table_cell_selected {
    //         base 255 255 255
    //         background 40 42 54
    //         emphasis_0 255 184 108
    //         emphasis_1 139 233 253
    //         emphasis_2 80 250 123
    //         emphasis_3 255 121 198
    //     }
    //     table_cell_unselected {
    //         base 255 255 255
    //         background 0 0 0
    //         emphasis_0 255 184 108
    //         emphasis_1 139 233 253
    //         emphasis_2 80 250 123
    //         emphasis_3 255 121 198
    //     }
    //     list_selected {
    //         base 255 255 255
    //         background 40 42 54
    //         emphasis_0 255 184 108
    //         emphasis_1 139 233 253
    //         emphasis_2 80 250 123
    //         emphasis_3 255 121 198
    //     }
    //     list_unselected {
    //         base 255 255 255
    //         background 40 42 54
    //         emphasis_0 255 184 108
    //         emphasis_1 139 233 253
    //         emphasis_2 80 250 123
    //         emphasis_3 255 121 198
    //     }
    //     frame_selected {
    //         base 80 250 123
    //         background 0
    //         emphasis_0 255 184 108
    //         emphasis_1 139 233 253
    //         emphasis_2 255 121 198
    //         emphasis_3 0
    //     }
    //     frame_unselected {
    //         base 7
    //         background 0
    //         emphasis_0 0
    //         emphasis_1 0
    //         emphasis_2 0
    //         emphasis_3 0 0 0
    //     }
    //     frame_highlight {
    //         base 255 184 108
    //         background 0
    //         emphasis_0 255 184 108
    //         emphasis_1 255 184 108
    //         emphasis_2 255 184 108
    //         emphasis_3 255 184 108
    //     }
    //     exit_code_success {
    //         base 80 250 123
    //         background 0
    //         emphasis_0 139 233 253
    //         emphasis_1 0 0 0
    //         emphasis_2 255 121 198
    //         emphasis_3 98 114 164
    //     }
    //     exit_code_error {
    //         base 255 85 85
    //         background 0
    //         emphasis_0 241 250 140
    //         emphasis_1 0
    //         emphasis_2 0
    //         emphasis_3 0
    //     }
    //     multiplayer_user_colors {
    //         player_1 255 121 198
    //         player_2 98 114 164
    //         player_3 0
    //         player_4 241 250 140
    //         player_5 139 233 253
    //         player_6 0
    //         player_7 255 85 85
    //         player_8 0
    //         player_9 0
    //         player_10 0
    //     }
    }
}

session_serialization false
serialization_interval 1

keybinds {
  tmux {
    bind "Ctrl a" { Write 1; SwitchToMode "Normal"; }
    bind "[" { SwitchToMode "Scroll"; }
    bind "-" { NewPane "Down"; SwitchToMode "Normal"; }
    bind "|" { NewPane "Right"; SwitchToMode "Normal"; }
    bind "1" { GoToTab 1; SwitchToMode "Normal"; }
    bind "2" { GoToTab 2; SwitchToMode "Normal"; }
    bind "3" { GoToTab 3; SwitchToMode "Normal"; }
    bind "4" { GoToTab 4; SwitchToMode "Normal"; }
    bind "5" { GoToTab 5; SwitchToMode "Normal"; }
    bind "6" { GoToTab 6; SwitchToMode "Normal"; }
    bind "7" { GoToTab 7; SwitchToMode "Normal"; }
    bind "8" { GoToTab 8; SwitchToMode "Normal"; }
    bind "9" { GoToTab 9; SwitchToMode "Normal"; }
    bind "0" { GoToTab 10; SwitchToMode "Normal"; }
  }
  shared_except "tmux" "locked" {
    bind "Ctrl a" { SwitchToMode "Tmux"; }
  }
}


plugins {
  zjstatus location="file:/Users/daniel/Developer/Rust/zjstatus/target/wasm32-wasip1/release/zjstatus.wasm" {
    hide_frame_for_single_pane "true"

    // catppuccin
    color_bg     "#0e0801"
    color_fg     "#9399B2"
    color_fg_dim "#6C7086"
    color_blue   "#89b4fa"
    color_orange "#ffc387"

    // gruvbox-dark
    color_bg     "#1d2021"
    color_fg     "#ebdbb2"
    color_fg_dim "#928374"
    color_orange "#fe8019"

    // rose-pine
    // color_bg     "#33362E"
    // color_fg     "#9ccfd8"
    // color_fg_dim "#56949f"
    // color_blue   "#31748f"
    // color_orange "#f6c1 [...]

2025-01-31 17:20 UTC, DeaconDesperado commented
> EDIT: seems like we have another snapshot to update: https://github.com/zellij-org/zellij/actions/runs/13020325545/job/36471935504?pr=3242#step:11:2117

Yes looks like this is during the e2e test suite... I've only been triggering tests with `cargo xtask test`.  I think awhile back I had some issues running the e2e tests on OSX, will give another try else manually update the snapshot.

2025-01-31 19:22 UTC, imsnif commented
No worries @DeaconDesperado - please don't update the snapshots manually, it's a lot of needless meticulous work. If it comes to it I'll do it.

If you could take a look at the issues @dj95 found though, that would be great.

2025-01-31 22:18 UTC, DeaconDesperado commented
Hey @dj95 I really appreciate you giving this a go and for the kind words on the implementation 😄 

1. I have pushed up a fix for this.  It was a combination of a wrong translation of a color (bg -> black for tables and lists in unselected mode) and a missing branch for handling `opaque` in table specifically.  Thanks for that catch!
2.  I added a fix for this as well... just needed to correct the padding to get explicit widths set right.
3. This is by design, as the first row is styled with `table_title`.  When using an older theme definition, this should use the color specified as `green` in the config for the text color.  This is to [match the existing implementation.](https://github.com/zellij-org/zellij/blob/main/zellij-server/src/ui/components/mod.rs#L90)  It looks like in your custom theme you have this color set equivalently to `yellow` + `orange`?

With fixes + demo for ribbon positioning:

<details>
<summary>Screenshot</summary>
<br>

![image](https://github.com/user-attachments/assets/4ac7b175-a295-48c8-bd46-f67cdd08e857)

</details>

@imsnif I didn't manage to get the e2e tests running to generate that specific insta snapshot.  Would def appreciate if you could add that commit for me... I looked through the others in there and it seemed to be just that one test that logs out the `Palette`.

2025-01-31 23:12 UTC, dj95 commented
Awesome! Thanks a lot for your quick fix @DeaconDesperado . Now it looks exactly the same.

2025-02-03 20:26 UTC, DeaconDesperado commented on zellij-utils/src/data.rs
> +                base: PaletteColor::EightBit(7),
Added a fix for this that makes the `frame_unselected` style optional.

2025-02-03 20:54 UTC, DeaconDesperado commented
Pushed up a fix for the optional styling of `frame_unselected`.  I also wanted to leave a quick note on the second new commit above, as it resulted from @dj95's feedback, and I believe it may resolve an existing ambiguity in the API?

When setting an explicit `width` for a ribbon with `print_ribbon_with_coordinates`, the width value is now inclusive of any padding added (whitespace + arrow chars if enabled).  This has the effect that `width` dictates the total width of the element and not just the text within it, so the existing fixture with value of `10` would wrap too early and cut off the `1` in `ribbon 1` (and so has been corrected to be wider).

I think this is the correct behavior, matching also what @dj95 as a user expected.  But it bears mention there's nowhere I could find in the zellij codebase where the explicit width setting is used.  It did seem that for several components though, there is a habit of adding `4` to `y` offsets to accommodate for the extra characters, which would match in terms of intention.  This also renders consistently when arrow chars are enabled or disabled.

2025-02-03 21:04 UTC, dj95 commented
Im not sure if I understood your comment 100%. But in the plugin code, I set the width to 12, which includes the chars for the arrow itself, as the string "ribbon 1" contains 8 chars und you then need 1 for spacing and 1 for the arrow on each side. 

But I agree, that it's much more intuitive, when you just need to specify the text width and do not keep the 4 extra chars for the arrow around it in mind. Although this would impose a breaking change in the behavior of the UI components.

2025-02-07 10:59 UTC, imsnif commented
Thanks @dj95 for helping iterate over this and catching some last minute issues!

I have updated the snapshot and everything looks great. I'm going to merge this now.

A very big thank you goes to @DeaconDesperado for his excellent work and dedication throughout this long and non-trivial contribution. You have made the application much better and I'm looking forward to seeing what theme authors come up with. It has been a privilege.

If you would like to stick around and contribute more, now or in the future - just reach out and let me know what you'd like to work on (either here, by email or on Discord/Matrix). All the best!

2025-02-07 10:59 UTC, merged

2025-02-07 13:22 UTC, DeaconDesperado commented
Thanks so much @imsnif!  

If it makes sense, I think migrating some of the older UIs to the UI components might be a natural extension of what I've learned here and a reasonable thing to contrib next.

Shall we close #2297?