Switching Tabs if there's no pane in the direction
zellij-org/zellij pull request #471
Opened 2021-05-07 21:21 UTC by dantepippi

New behavior for Alt + 'h' and Alt + 'l': will switch tabs if there are no available panes in the direction.
Closes #464

2021-05-08 12:50 UTC, kunalmohan requested changes
Hey! Thanks for the PR. This looks good! I haven't tested it yet though; a couple of small changes before I do that.

You'll have to create a new `match` arm with the new `Action` variant in https://github.com/zellij-org/zellij/blob/7b5e728f9db7d82d9282265bb8fa35d7b05e5622/src/common/input/handler.rs#L106
And check for the direction. Since we might be switching tabs if the direction is left or right, we'll have to block the input thread in those cases (using the two `command_is_executing` methods) to ensure atomicity for those actions. Once these are completed, we unblock the input thread by sending the `UnblockInputThread` message.

We should also have tests for these changes :)

2021-05-08 16:20 UTC, dantepippi commented on src/server/mod.rs
> +                                screen
Greetings @kunalmohan! Thank you for taking your time to review the code.

Please take a look at the changes you've requested.

I don't think we need to check for the direction as the action MoveFocusOrTab() is only called with directions left or right (never with up and down), so we can always ensure it is an atomic operation. :)

I'm trying to figure out the test framework to create those new tests.

2021-05-08 16:20 UTC, dantepippi commented on src/server/mod.rs
> +                                screen
Done! :)

2021-05-10 15:13 UTC, kunalmohan approved these changes
LGTM! @dantepippi this is a great feature with a neat implementation! Thank you for your patience!

2021-05-10 15:14 UTC, merged