Don't rename 'unnamed' tabs upon deletion of other tabs
zellij-org/zellij pull request #554
Opened 2021-05-31 15:11 UTC by AdaShoelace

This PR aims to solve issue #474.
I decided to put the logic in `Tab::new`. This approach felt the "cleanest" to me.
If this breaks any style guides or should be done differently for other reasons please let me know and I'll change it.

2021-05-31 17:40 UTC, a-kenji commented on zellij-server/src/tab.rs
> +            name: if name.is_empty() {
I would prefer the initialization here just like the `panes` are initialized.

`let name =` prior and then keep the name here.

2021-06-01 07:35 UTC, a-kenji requested changes
Thank you, this is already pretty great and
I think including it in `tab` does make a lot of sense!

There is still one thing that I would like to see a little bit different:

When opening a tab and not really caring about the name,
I think I know what you want to convey with the (unnamed), but I think it
does take up too much space. And should be fine with being omitted.

2021-06-01 07:43 UTC, AdaShoelace commented
> Thank you, this is already pretty great and
> I think including it in `tab` does make a lot of sense!
> 
> There is still one thing that I would like to see a little bit different:
> 
> When opening a tab and not really caring about the name,
> I think I know what you want to convey with the `(unnamed)`, but I think it
> does take up too much space. And should be fine with being omitted.

"(unnamed)" has been removed.

2021-06-01 07:44 UTC, a-kenji approved these changes
Awesome, thank you!

2021-06-01 08:23 UTC, merged

2021-06-23 15:47 UTC, ammkrn commented
@a-kenji 

It seems like some underlying map of tabs to numbers still exhibits the old behavior. If I have `tab1, tab2, tab3, tab4` and close`tab2`, the remaining tabs are `tab1, tab3, tab4`, but in tab mode, pressing the `2` key jumps to `tab3` and the `3` key jumps to `tab4`.

If other people are observing this I can take a look at it. Hints for where to look would be appreciated.

2021-06-23 16:00 UTC, a-kenji commented
@ammkrn,
This is correct, but sadly still confusing behaviour.
The tabs are now named that way by default, but the keys
map to the position in the tab. I hope with #557 we can show 
the number of the tab and then the name of the tab with a 
running program/shell behind.

I believe we want (am happy about more input):
To go to a specific tab-name: #379. (An ongoing pr atm).
To go to a specific tab#. (The current 2 behaviour).

I imagined this here to be in scope of #557:
To show the number of the current tab.
To show the name of the current tab. (possibly with name of currently running process)

2021-06-24 15:03 UTC, ammkrn commented
Thanks for clearing that up; I look forward to seeing how those solutions work out.