Proposal: Allow use of system clipboard
zellij-org/zellij pull request #996
Opened 2022-01-07 14:48 UTC by djpate

Currently the copy to clipboard is done using OSC52 which is not supported by some linux terminals like `gnome-terminal` or `xfce4-term` etc. 

The proposal here is to allow for a flag called `--use-system-clipboard` which will switch away from OSC52 back to using `xclip`. This is done using the `copypasta-ext` crate.

This is my first ever rust code so I'm happy to hear any feedback.

This was tested on Ubuntu using `gnome-terminal`

2022-01-07 16:30 UTC, imsnif requested changes
Hey, on the whole this looks great - I'm especially impressed since you mentioned you don't know Rust - so kudos on getting into the code-base so easily!

I left one minor nitpick. Otherwise, we use `rustfmt` to lint our code and clippy for some additional fixes. There are instructions about how to run them in CONTRIBUTING.md (that's why part of the tests here are failing).

Lastly - I haven't tested this yet, so would like to manually do so (I'll get to it over the weekend), and assuming the tests pass (at the time of writing they're still running) - this should be good to go.

Thanks very much for taking the time to do this!

2022-01-07 16:30 UTC, imsnif commented on zellij-server/src/screen.rs
> +    config_options: Box<Options>
Can we just pass the `use_system_clipboard` option instead of everything?

2022-01-07 16:46 UTC, tlinford commented
Awesome, thanks for working on this!

There is one thing that needs sorting out, it looks like for now this will work on linux with x11, but not macos, windows, or linux with wayland.

As an example here is how alacritty is doing the setup: https://github.com/alacritty/alacritty/blob/531e494cf9a90de91dbbb84cb6cfc3158b78f1f2/alacritty/src/clipboard.rs#L8.

2022-01-08 01:22 UTC, djpate commented
Perfect. Thanks for the feedback. I'll try to work on it this weekend.

2022-01-10 20:00 UTC, djpate commented
Updated.

2022-01-10 20:31 UTC, tlinford commented
Cool!
Tested it on wayland, and I had to install `wl-clipboard` to get it working (was getting `Error: thread 'screen' panicked at 'called `Result::unwrap()` on an `Err` value: NoBinary': zellij-server/src/tab/mod.rs:1926` without).

I guess this is because the alacritty fork of copypasta doesn't work in a terminal program, so you went with copypasta-ext instead?

Ideally I'd prefer not to have to depend on an external binary being present, but IMO this is an acceptable tradeoff (as long as we document it) for the time being - @imsnif thoughts on this?

2022-01-10 21:20 UTC, djpate commented
@tlinford thanks for testing it out. Works on x11 without additional libraries but yeah I guess wayland is different.

I tried with copypasta initially but I couldn't get it to work. No errors just nothing in the copy buffer.

2022-01-11 17:48 UTC, tlinford commented
Hey @djpate,
we talked about this in our weekly meeting, and would like to merge this great feature asap.
The one thing blocking this is the panic when `wl-clipboard` is not found.

The best way to work around this potential problem would be to make the statusbar plugin display an error message if `DisplayServer::select().try_context()` gives an `Err`. This could be done by replicating the way the 'Text copied to clipboard' message is displayed.

If you want to go this route, you could check out to how `Event::CopyToClipboard` is used.

As a simpler alternative if you feel like that is too much work, for now it would be fine to just swallow the error and move on, would be better than crashing :)

2022-01-11 18:55 UTC, djpate commented
@tlinford I'll look into outputting the error in the status bar.

2022-01-11 20:32 UTC, djpate commented
@tlinford I think that should do it but I can't repro to test... could you take a look?

2022-01-11 20:48 UTC, tlinford commented
@djpate close, and my bad I pointed you at the wrong line, the error is coming from here:
```
clipboard_context
                .set_contents(selection.to_owned())
                .unwrap();
```

Although it's probably a good idea at this point to handle both error cases.

2022-01-11 21:09 UTC, tlinford commented
```
 let res = DisplayServer::select()
                .try_context()
                .ok_or_else(|| "could not get clipboard provider".into())
                .and_then(|mut ctx| ctx.set_contents(selection.to_owned()));

            if res.is_err() {
                system_clipboard_failure = true
            }
```

Did some poking around, and came up with this to handle both the Option and then the result, the message in status bar looks great :)

2022-01-11 21:30 UTC, djpate commented
Awesome. Updated the code

2022-01-12 10:56 UTC, tlinford approved these changes

2022-01-12 14:41 UTC, djpate commented
@tlinford @imsnif Pipeline is fixed. I had to add a couple of ubuntu packages for it to pass.

Everything should be good now.

2022-01-12 15:43 UTC, imsnif commented
Hey @djpate - could you briefly explain about those ubuntu packages you had to add?

2022-01-12 15:47 UTC, djpate commented
@imsnif I believe they are required for copypasta-ext to compile. They are packages for xcb which is x11 C bindings.

2022-01-12 15:50 UTC, imsnif commented
Does that mean they will be a requirement for Zellij now on all platforms, or is this just a headless thing due to the CI? Because the former is a bit of a dealbreaker, I'm afraid :/

2022-01-12 16:03 UTC, djpate commented
I'm not adding it to macosx pipeline and it compiled fine. 

Anyone compiling on Linux is gonna need those dependencies.

2022-01-12 16:09 UTC, imsnif commented
Right - so I'm really sorry this came up only at this late stage, but we can't go forward with such a requirement. This would make it more difficult for new users to install the app.

The way I see it, we have a couple of options to move forward:
1. Find out if we can somehow require these at runtime and then give an error similar to what we did with Wayland above
2. Find a different solution/crate that interacts with the clipboard in a different way (not sure this exists or is possible?)

What do you think? Or maybe you have another idea?

2022-01-12 16:11 UTC, djpate commented
I understand. This is deep in the copypasta crate so I'm not sure I can figure that one out. I'll go back to the drawing board but I don't have have a good idea yet :)

2022-01-12 16:16 UTC, djpate commented
I can't see the copypasta people requiring this package in their GitHub pipelines. Maybe I'm missing something. I'll try to take another look

2022-01-12 16:30 UTC, tlinford commented
damn :/
looks like it's a runtime dependency as well, get this on a ubuntu server vm:
```
./zellij: error while loading shared libraries: libxcb-xfixes.so.0: cannot open shared object file: No such file or directory
```

2022-01-12 16:34 UTC, imsnif commented
> damn :/ looks like it's a runtime dependency as well, get this on a ubuntu server vm:

This is good, actually. If we can bypass the compile time requirements, get this error at runtime and communicate it to the user we're gold.

2022-01-12 20:07 UTC, djpate commented
ok I tracked it down to [](https://github.com/quininer/x11-clipboard which) is a dependency of copypasta. Not much more I can do with my limited knowledge of Rust. I'll use my fork for me in the mean time haha. 

Feel free to close the PR :cry:

2022-01-12 20:32 UTC, tlinford commented
One last shot going with copypasta (I'm testing this out right now) - we can disable the `x11-fork` feature and use `x11-bin` instead. That way we should get the same behaviour as with wayland, and copying on x11 will rely on `xclip` and `xsel` being installed.

2022-01-13 08:36 UTC, tlinford commented
no luck unfortunately, tried using copypasta-ext with:
```
copypasta-ext = { version = "0.3.7", default-features = false, features = [
    "x11-bin",
    "wayland-bin",
] }
```
but it still ends up pulling in x11-clipboard.

2022-01-13 09:24 UTC, imsnif commented
Is it something we can fix upstream with a PR in copypasta

2022-01-13 15:27 UTC, tlinford commented
Hey @djpate - sorry that the copypasta way turned out to be problematic, really appreciate all the effort.
Another idea: we could take insipiration from tmux once again, and go for something like `copy-command` (https://github.com/tmux/tmux/wiki/Clipboard#how-to-configure---tmux-32-and-later).

Basically we would need to allow the user to set a command that the selection can be piped into - also kind of similar to how copypasta-ext was handling things on wayland.
This way we don't need to depend on anything, and we can keep the awesome error reporting. what do you say?

2022-01-13 15:30 UTC, djpate commented
@tlinford I really like this idea. Seems to be very flexible. Let me try to see if I figure this one out.

Thanks for the mentoring on this.

2022-01-13 21:03 UTC, djpate commented
So I got this to work using `xclip`.

seems like it would be trivial to set it up with `wl-copy` or others.


the only thing I'm wondering about it is how to configure it.

for xclip you need to configure the command: `xclip` and the args to that command `-sel` and `clip` so that means in the config file we could do something like

```yaml
system_clipboard:
  command: xclip
  args:
    - "-sel"
    - clip
```

but that would make it very tricky to configure it from the cli's perspective.

Any thoughts?

2022-01-14 10:30 UTC, tlinford commented
@djpate I'm not very familiar with structopt, but maybe quoting the command with it's args works?
something like --copy-command "xclip -sel clip"

2022-01-14 18:22 UTC, djpate commented
@tlinford @imsnif It's me again, I've switched it use `--copy-command`

Seems to work fine with `xclip` and `wl-copy`.

The issue I have is that I can't get the error to display for me.

```zellij options --copy-command "foobar"```

does not display the failure message for some reason.

2022-01-14 21:41 UTC, tlinford commented
Looks like we're getting there at last :)

> does not display the failure message for some reason.
Did a quick test with
```❯ cargo make run options --copy-command "does-not-exist"```
and I'm seeing the expected error, while it seems to be also working great using `wl-copy` or `wl-copy -p`, so I'm not sure why you'r not seeing the error.

2022-01-14 21:54 UTC, djpate commented
@tlinford no you're right it's working. Not sure what I was doing wrong.

Okay I think we're there :) @imsnif what do you think?

2022-01-14 22:16 UTC, imsnif commented
I haven't taken a look yet, but if @tlinford says it's good to go, I'm happy.

Just to make sure: we've gotten rid of the `use_system_clipboard` flag now that we're explicitly passing the command, right?

Otherwise, once we merge this we need to make sure to update our documentation. Might be nice to add it to the troubleshooting section. Very cool that this is happening! Thank you all for your work. I think it's a really cool solution.

2022-01-14 22:47 UTC, djpate commented
@imsnif That's correct we only have a new option called `--copy-command`. If not supplied we use OSC52.

2022-01-15 10:01 UTC, tlinford approved these changes

2022-01-15 11:38 UTC, tlinford commented
@imsnif - just a note, the e2e ci tests seems to be flaky again, for me they are always passing locally but had to do multiple runs on this: https://github.com/zellij-org/zellij/actions/runs/1699020751/attempts/3
@djpate LGTM! Thanks again for this.

2022-01-15 11:38 UTC, merged

2022-01-15 13:31 UTC, djpate commented
@tlinford @imsnif Thanks a lot. 

Amazing app you have built.